// ── Lexicon ──────────────────────────────────────────────────
// One word pool per house theme. Callsign's own picks from public sources in
// the same vein as each manufacturer's in-game names. Every in-game proper
// name is left out on purpose; the test harness checks the pools against the
// real part list, and canon.js rerolls any designation that lands on one.

const words = (s) => s.trim().split(/\s+/);
const lines = (s) => s.trim().split(/\s*\|\s*/);

// BAWS: pen names from the wider circle of Basho's school. The Ten Disciples
// the game uses (and Basho himself) are left out; Shiko is the one it skipped.
export const POETS = words(`
  SHIKO SORA BONCHO OTOKUNI CHIGETSU IZEN TOKOKU KAKEI ROTSU SHADO SHOHAKU
  ISSHO MASAHIDE KYOKUSUI UKO TORIN SODO SENNA RIYU DOHO RANRAN SOHA SONOME OTSUYU`);

// Balam: surnames of noted entomologists.
export const ENTOMOLOGISTS = words(`
  FABRE LATREILLE KIRBY SPENCE WESTWOOD BATES MERIAN SWAMMERDAM REAUMUR
  FABRICIUS MEIGEN BURMEISTER ERICHSON LACORDAIRE COMSTOCK RILEY WHEELER NABOKOV
  DOUBLEDAY HAGEN LECONTE MELSHEIMER PACKARD WALSH FORBES FERNALD SNODGRASS
  WIGGLESWORTH TILLYARD MACLEAY WILLISTON MICHENER EISNER DETHIER CARPENTER`);

// Dafeng: asterisms of the Purple Forbidden and Supreme Palace enclosures, in
// hyphenated pinyin. Guards, walls and weapons for weapons; offices and
// buildings for the inner parts, the way the game splits them.
export const ASTERISMS_GUARD = words(`
  TIAN-BANG LANG-JIANG LANG-WEI ZUO-YUAN YOU-YUAN CHANG-YUAN CONG-GUAN NEI-PING
  TIAN-ZHU BEI-DOU SI-FU LIU-JIA TIAN-YI TAI-YI`);
export const ASTERISMS_OFFICE = words(`
  CHUAN-SHE NEI-JIE TIAN-CHU NEI-CHU WEN-CHANG TIAN-CHUANG SHANG-SHU DA-LI
  JIU-QING SAN-GONG SAN-SHI TAI-ZUN XING-CHEN TAI-ZI YE-ZHE ZHU-SHI NU-SHI YU-NU
  BA-GU HUA-GAI WU-DI-ZUO BEI-JI YIN-DE TIAN-LI WU-ZHU-HOU`);
export const ASTERISMS = [...ASTERISMS_GUARD, ...ASTERISMS_OFFICE];

// Schneider: German bird names (umlauts written ue, oe), and for boosters a
// part of the bird.
export const BIRDS = words(`
  SPERBER HABICHT MILAN BUSSARD FALKE UHU KAUZ SPECHT AMSEL DROSSEL LERCHE
  SCHWALBE STORCH KORMORAN EISVOGEL ZAUNKOENIG PIROL WIEDEHOPF SEEADLER
  WANDERFALKE ROTMILAN TURMFALKE BAUMFALKE GOLDAMMER DOHLE ELSTER RABE SEGLER
  MOEWE SCHWAN FISCHADLER STEINADLER KIEBITZ BRACHVOGEL NEUNTOETER`);
export const PLUMAGE = words(`
  SCHWINGE FEDER SCHNABEL KRALLE STEISS SCHWANZ DAUNE KIEL SPIEGEL KROPF HAUBE
  SCHOPF GEFIEDER DECKFEDER HANDSCHWINGE ARMSCHWINGE`);

// Elcano: Spanish. Steadfast, fortified and early-light words for the body,
// weather for the weapons.
export const SPANISH_STEADY = words(`
  CONSTANCIA TENACIDAD ENTEREZA TEMPLANZA LEALTAD BRAVURA TESON AUDACIA MURALLA
  BALUARTE ALCAZAR TORREON ATALAYA CIUDADELA ALMENA CUMBRE ALBOR AMANECER
  MADRUGADA LUCERO ALBORADA CENTINELA VIGIA`);
export const SPANISH_WEATHER = words(`
  RELAMPAGO TORMENTA GRANIZO NEVADA BRUMA NIEBLA RAFAGA CICLON CHUBASCO AGUACERO
  GALERNA CEFIRO LEVANTE PONIENTE SIROCO CENTELLA ESCARCHA HELADA VENDAVAL
  BORRASCA RAYO TRONADA`);

// RaD: job descriptions for the 2000 scouts, heavy plant for the 3000
// construction rigs, courses of a meal for the 5000 combat frames.
export const RAD_SCOUT = lines(`
  LOOKOUT | SPOTTER | SURVEYOR | SIGNALMAN | LINEMAN | PROSPECTOR | SWEEPER |
  FETCHER | NIGHT WATCH | TRAIL GUIDE | ODD JOBBER | GOPHER | DOGSBODY | GRUNT`);
export const RAD_WORKS = lines(`
  BULLDOZER | BACKHOE | EXCAVATOR | PILEDRIVER | JACKHAMMER | STEAMROLLER |
  FORKLIFT | RIVETER | WELDER | SANDBLASTER | CEMENT MIXER | GRADER | DUMP TRUCK`);
export const RAD_COURSES = lines(`
  ENTREE | SORBET | DIGESTIF | CHEESE COURSE | PALATE CLEANSER | CANAPE |
  STARTER | SECOND HELPING | LEFTOVERS | PETIT FOUR | CHEF SPECIAL |
  TASTING MENU | DOGGY BAG | BREAD BASKET | AFTER DINNER MINT`);
export const RAD_BOOSTERS = lines(`
  PACKHORSE | JUMPSTART | BACKFIRE | KICKSTAND | OXCART | HOTFOOT | TAILWIND |
  24680 | 13579`);
// RaD weapons: idioms and job titles for things that go off.
export const RAD_IDIOMS = lines(`
  HOUSE CALL | LAST ORDERS | PARTY FAVOR | SMALL TALK | COLD OPEN | PLUS ONE |
  HAPPY HOUR | LOST CAUSE | GOOD NEIGHBOR | SPARE CHANGE | DEAD LETTER |
  HOUSEWARMING | LATE FEE | WAKE UP CALL | FRONT ROW | KIND REGARDS | BIG FINISH |
  SOFT LAUNCH | CLEAN SLATE | HOT TAKE | ICE BREAKER | GRAND OPENING |
  FAIR WARNING | OPEN HOUSE | DOOR PRIZE | PARTING GIFT | QUIET HOURS |
  BEDSIDE MANNER | SECOND OPINION | POTLUCK | SWAN SONG | BRIGHT SIDE |
  RAIN CHECK | FIELD TRIP | PEN PAL | GUEST LIST | WELCOME MAT | ENCORE |
  CURTAIN CALL | LAST DANCE | NO HARD FEELINGS | CHAPERONE | SOMMELIER |
  LIFEGUARD | BABYSITTER | NIGHTCAP`);

// Melinite: plain words that lean toward precious things and loud sounds.
export const MELINITE = lines(`
  RHODIUM | OSMIUM | PALLADIUM | PLATINUM | GARNET | TOPAZ | OPAL | SAPPHIRE |
  CAMEO | FILIGREE | HEIRLOOM | CROWN JEWEL | KEEPSAKE | SPLENDID | REGAL |
  OPULENT | GILDED | SOVEREIGN | HANDCLAP | DRUMROLL | FANFARE | CRESCENDO |
  TINNITUS | WHISTLER | DAWN CHORUS | NIGHTINGALE | BELLRINGER | THUNDERCLAP |
  HUBBUB | GIDDY | WOOZY | TIPSY | SWOON`);

// ALLMIND: frames are a word for the mind plus a Greek letter; weapons are
// English words with their vowels stripped.
export const MINDWORDS = words(`
  NOUS SENSE WILL WITS NERVE FOCUS DREAM GAZE HUNCH INSIGHT INSTINCT REFLEX
  PSYCHE REASON THOUGHT`);
export const TERSE = words(`
  HARBOR BEACON COMPASS LANTERN LEDGER ARCHIVE SENTINEL WARDEN MIRROR CIPHER
  VECTOR SIGNAL CANOPY RAMPART TALON HALBERD SABER LANCE RAPIER GLAIVE SPEAR
  TRIDENT BALLISTA CATAPULT BULWARK PALADIN HERALD MARSHAL CONSUL TRIBUNE
  PRAETOR LEGATE CENSOR NOMAD BASTION CITADEL SPARROW FALCON TEMPEST`);
export const GREEK = words('ALPHA BETA GAMMA DELTA');

// Institute IA parts: biology for the body, sky and light for the weapons.
export const IA_BODY = words(`
  CORNEA RETINA CORTEX SYNAPSE AXON PLEXUS MARROW ATRIUM VENTRICLE CILIA FASCIA
  ALVEOLI LYMPH TENDON SINEW VERTEBRA ANTENNA MANDIBLE THORAX CHRYSALIS CARAPACE
  SPIRACLE PUPA LARVA NYMPH ELYTRA PROBOSCIS HALTERE CUTICLE CAPILLARY`);
export const IA_SKY = words(`
  ZENITH NADIR PARALLAX ECLIPTIC CORONA QUASAR PULSAR EQUINOX SOLSTICE UMBRA
  PENUMBRA APOGEE PERIGEE MERIDIAN BLUESHIFT HALO AZIMUTH AFTERGLOW MAGNETAR
  PERIHELION STARLIGHT SUNDOG TWILIGHT AIRGLOW SUPERNOVA COMET METEOR`);

// Institute IB codes the game already stamps, kept out of generated letters.
export const IB_TAKEN = words('HAL WLT NGI CEL SOL');

// ── Callsign originals ───────────────────────────────────────
// Word pools for the houses Callsign made up (js/houses-callsign.js). Real,
// public names that read like science fiction; js/families.js cites a source
// for each. Every list was checked word by word against its source, and words
// whose generated acronyms read badly were dropped rather than blocked.

// Apojove: small bodies of the outer solar system under the IAU's rules.
// Jupiter's captured outer moons for frames: every name ends in A, E or O,
// which Apojove stamps as the orbit (prograde, retrograde, inclined).
export const JOVIAN_MOONS = words(`
  HIMALIA PANDIA CARPO EUPORIE EUPHEME MNEME EUANTHE HARPALYKE ORTHOSIE HELIKE ANANKE
  HERMIPPE PHILOPHROSYNE PASITHEE EURYDOME CHALDENE ISONOE KALLICHORE ERINOME EIRENE AITNE
  EUKELADE ARCHE TAYGETE CARME HERSE KALYKE HEGEMONE PASIPHAE SPONDE CYLLENE SINOPE AOEDE
  AUTONOE`);
// Neptune's moons, moons of bodies past Neptune, and named trans-Neptunian objects.
export const FAR_BODIES = words(`
  NEREID HALIMEDE LAOMEDEIA PSAMATHE HIPPOCAMP ARAWN RHADAMANTHUS LEMPO HIISI PAHA
  DEUCALION AYA CETO PHORCYS GOIBNIU ACTAEA RUMINA RITONA ACHLYS GONGGONG XIANGLIU
  MORS-SOMNUS OTRERA CLETE PRAAMZIUS DZIEWANNA TAOWU ZHULONG ALICANTO DYSNOMIA`);
// Weapons: Saturn's Gallic and Norse moons, then the centaurs. CENTAURS is
// also a marker list: a weapon named from it stamps C for centaur.
const SATURN_GIANTS = words(`
  ALBIORIX BEBHIONN ERRIAPUS TARVOS SKATHI SKOLL HYRROKKIN GREIP MUNDILFARI GRIDR
  BERGELMIR JARNSAXA NARVI SUTTUNGR HATI EGGTHER FARBAUTI THRYMR BESTLA AEGIR BELI GUNNLOD
  SKRYMIR ALVALDI KARI GEIRROD LOGE THIAZZI FORNJOT`);
export const CENTAURS = words(`
  PHOLUS ASBOLUS CHARIKLO HYLONOME ELATUS THEREUS PELION CYLLARUS BIENOR ECHECLUS CRANTOR
  APHIDAS ORIUS RHIPHONOS EURYTUS PETRAIOS`);
export const GIANTS_AND_CENTAURS = [...SATURN_GIANTS, ...CENTAURS];

// Umklapp: quasiparticles, field knots and bound states for the body,
// hypothetical particles and superpartners for the weapons.
export const EXOTIC_BODIES = words(`
  ANGULON BIEXCITON BION BOGOLON CHARGON CONFIGURON DISLON DOUBLON DROPLETON HOPFION
  NEMATICON OSCILLON PHASON PHONITON PLASMARITON PLASMARON PLEXCITON SKYRMION TRIPLON
  WRINKLON INSTANTON CALORON MERON SPHALERON RENORMALON GLUEBALL DIQUARK TETRANEUTRON
  DIPROTON STRANGELET`);
export const EXOTIC_FIELDS = words(`
  CURVATON DILATON GRAVIPHOTON GRAVIVECTOR GRAVISCALAR HYPERPHOTON INFLATON MAJORON
  PRESSURON SYMMETRON LEPTOQUARK DILATINO GLUINO GRAVITINO CHARGINO GOLDSTINO SGOLDSTINO
  SNEUTRINO SMUON STAU SQUARK SLEPTON SFERMION GAUGINO QUINTAXION POMERON ODDERON FAMILON
  BRANON PLEKTON PRIMON RISHON CHERNON UNPARTICLE PARAPARTICLE SPURION`);

// Vastitas: habitats and megastructures for frames; drives, sails, beams
// and launchers for everything else.
export const MEGASTRUCTURES = lines(`
  TOPOPOLIS | WORLD HOUSE | ORBITAL RING | SPACE FOUNTAIN | SPACE TOWER | LAUNCH LOOP |
  SPACE RUNWAY | STELLAR ENGINE | ATLANTROPA | STATITE | SPACESTEAD | CYCLER |
  WORLD SHIP | ISLAND ONE | ISLAND THREE | LEWIS ONE | WET WORKSHOP | AEROSTAT |
  SPACE SUNSHADE | SOLETTA | ZNAMYA | OPSEK | RECTENNA | HELIOSTAT | MAGLIFTER |
  VORTEX ENGINE | ORBITAL STEAD | SAHARA SEA | RED SEA DAM`);
export const DRIVES = lines(`
  RESISTOJET | HELICON | VACUUM ARC | PULSED PLASMA | PLASMA MAGNET | GAS CORE |
  LIQUID CORE | PARTICLE BED | PHOEBUS | TIMBERWIND | KLYSTRON | GYROTRON | HYPERGOLIC |
  TRIPROPELLANT | EXPANDER CYCLE | AEROBRAKING | AEROCAPTURE | LASER THERMAL |
  SLINGATRON | LIGHT-GAS GUN | HASTOL | MAGBEAM | MAGSAIL | ELECTRIC SAIL | FISSION SAIL |
  STELLASER | STARWISP | PHOTON ROCKET | STAR LIFTING | LASER BROOM | PELLET BEAM |
  MASS BEAM | ROCKOON`);

// Quadnil: IUPAC placeholder names for elements 119 and up, and the working
// vocabulary of the island of stability for the weapons.
export const SUPERHEAVY = words(`
  UNUNENNIUM UNBINILIUM UNBIUNIUM UNBIBIUM UNBITRIUM UNBIQUADIUM UNBIHEXIUM UNBIOCTIUM
  UNTRINILIUM UNTRIUNIUM UNTRIBIUM UNTRITRIUM UNTRIQUADIUM UNTRIHEXIUM UNTRIOCTIUM
  UNQUADNILIUM UNQUADUNIUM UNQUADBIUM UNQUADTRIUM UNQUADHEXIUM UNQUADOCTIUM UNQUADENNIUM
  UNPENTUNIUM UNPENTBIUM UNPENTTRIUM UNPENTHEXIUM UNPENTOCTIUM UNPENTENNIUM UNHEXNILIUM
  UNHEXBIUM UNHEXTRIUM UNHEXQUADIUM UNHEXSEPTIUM UNHEXOCTIUM UNHEXENNIUM UNSEPTUNIUM`);
export const ISLAND_PHYSICS = lines(`
  DOUBLY MAGIC | SHELL CLOSURE | SHELL EFFECT | QUASIFISSION | HOT FUSION |
  CLUSTER DECAY | DECAY CHAIN | PENINSULA | ISTHMUS | QUARK MATTER | R-PROCESS |
  FERMIUM GAP | EXIT CHANNEL | NEUTRON FLUX | NEUTRON EXCESS | SUPERDEFORMED |
  HYPERDEFORMED | TOROIDAL | SUPERCRITICAL | PAIR CREATION | PAIR BREAKING | ISOTONE |
  ISODIAPHER | BORROMEAN | PHOTOFISSION | SPALLATION | DRIP LINE | FISSILITY |
  RADIOGENIC | SUBSHELL | SPIN-ORBIT | MASS EXCESS | LIQUID DROP | NUCLEAR ISOMER |
  EVEN-EVEN | BARE NUCLEUS`);

// Peristome: genera of plants that look off-world. Cycads and stone plants,
// parasites and fungus-fed plants, then carnivores and carrion flowers.
export const FLORA_BODIES = words(`
  BOWENIA CERATOZAMIA CYCAS DIOON ENCEPHALARTOS LEPIDOZAMIA MACROZAMIA MICROCYCAS
  STANGERIA ZAMIA WELWITSCHIA PLEIOSPILOS FENESTRARIA FRITHIA ARGYRODERMA TITANOPSIS
  DINTERANTHUS GIBBAEUM LAPIDARIA TANQUANA ALOINOPSIS NANANTHUS CHEIRIDOPSIS FAUCARIA
  STOMATIUM OOPHYTUM MONILARIA DRACOPHILUS PSAMMOPHORA MITROPHYLLUM`);
export const FLORA_HIDDEN = words(`
  HYDNORA PROSOPANCHE BALANOPHORA CORYNAEA HELOSIS LANGSDORFFIA OMBROPHYTUM RHOPALOCNEMIS
  SARCOPHYTE THONNINGIA DACTYLANTHUS MYSTROPETALON RHIZANTHES SAPRIA BDALLOPHYTUM CYTINUS
  APODANTHES PILOSTYLES MITRASTEMON LENNOA PHOLISMA CUSCUTA AEGINETIA CISTANCHE HYOBANCHE
  LATHRAEA OROBANCHE ARCEUTHOBIUM CASSYTHA THISMIA AFROTHISMIA ARACHNITIS RHIZANTHELLA
  TRIURIS SCIAPHILA LACANDONIA MONOTROPA SARCODES ALLOTROPA GASTRODIA EPIPOGIUM GEOSIRIS
  OXYGYNE GYMNOSIPHON`);
export const FLORA_TRAPS = words(`
  ALDROVANDA BROCCHINIA BYBLIS CATOPSIS CEPHALOTUS DARLINGTONIA DROSERA DROSOPHYLLUM
  GENLISEA HELIAMPHORA PINGUICULA RORIDULA STYLIDIUM TRIANTHA TRIPHYOPHYLLUM UTRICULARIA
  STAPELIA BULBOPHYLLUM SAPRANTHUS BOUCEROSIA ECHIDNOPSIS TIPUTINIA PIARANTHUS
  PSEUDOLITHOS HELICODICEROS LYSICHITON SYMPLOCARPUS ARISTOLOCHIA TACCA MASDEVALLIA`);

// Siboga: vent, seep, whale-fall and trench genera for frames; microbes of
// heat, acid, salt, sulfur, metal and radiation for everything else.
export const ABYSSAL_FAUNA = words(`
  RIFTIA TEVNIA RIDGEIA OASISIA ESCARPIA OSEDAX ALVINELLA PARALVINELLA OPHRYOTROCHA
  CHRYSOMALLON LEPETODRILUS OSTEOPELTA BATHYMODIOLUS CALYPTOGENA VESICOMYA ACHARAX ACESTA
  ALVINOCARIS RIMICARIS MUNIDOPSIS BYTHOGRAEA CHACEON BATHYNOMUS ALICELLA HIRONDELLEA
  EURYTHENES COLOSSENDEIS CHIRIDOTA SCOTOPLANES ENYPNIASTES PSYCHROPOTES GRIMPOTEUTHIS
  MAGNAPINNA STYGIOMEDUSA SYRINGAMMINA EUPLECTELLA MONORHAPHIS RHIZAXINELLA DYSOMMINA
  PSEUDOLIPARIS BATHYPTEROIS BASSOZETUS DIRETMUS HAPLOPHRYNE EURYPHARYNX`);
export const EXTREMOPHILES = words(`
  HALOQUADRATUM HALOFERAX HALORUBRUM HALOARCULA NATRIALBA NATRINEMA NATRONOMONAS
  SULFOLOBUS STYGIOLOBUS METALLOSPHAERA ARCHAEOGLOBUS FERROGLOBUS GEOGLOBUS FERROPLASMA
  GEOGEMMA PALAEOCOCCUS NANOARCHAEUM NANOBDELLA INFIRMIFILUM AQUIFEX SULFUROVUM BEGGIATOA
  THIOPLOCA CHLOROFLEXUS GEOBACILLUS CUPRIAVIDUS PSYCHROBACTER RUBROBACTER TERSICOCCUS
  PYROLOBUS PYRODICTIUM PYROCOCCUS PYROHABITANS AEROPYRUM IGNICOCCUS IGNISPHAERA
  ZESTOSPHAERA FERVIDICOCCUS CALDIVIRGA CALDISPHAERA CALDARCHAEUM MICROCALDUS ACIDILOBUS
  ACIDIPLASMA OXYPLASMA PICROPHILUS SULFURACIDIFEX`);

// Protyle: constellations the IAU did not keep in 1930 for frames; phantom
// elements, then forces and theories science gave up, for everything else.
export const LOST_SKY = lines(`
  ARANEA | DELTOTON | DENTALIUM | DUAE ALAE | FELIS | GALLUS | GRYPHITES | HIRUDO |
  LEO PALATINUS | LIMAX | LINUM PISCIUM | LUMBRICUS | MANIS | MONS MAENALUS |
  MUSCA BOREALIS | NORMA NILOTICA | PHOENICOPTERUS | PINNA MARINA | PISCIS NOTUS |
  PLUTEUM | POLOPHYLAX | QUADRATUM | RAMUS POMIFER | SCARABAEUS | SCIURUS VOLANS |
  TARABELLUM | VEXILLUM | TARANDUS | RANGIFER | TESTUDO | URANOSCOPUS | URNA | XIPHIAS`);
export const SPENT_SCIENCE = lines(`
  NEBULIUM | CORONIUM | ASTERIUM | AURORIUM | ARCONIUM | CYCLONIUM | DECIPIUM | DIDYMIUM |
  DIANIUM | ILMENIUM | PELOPIUM | HESPERIUM | AUSENIUM | LUCIUM | FLORENTIUM | SEQUANIUM |
  HELVETIUM | ANGLOHELVETIUM | BOHEMIUM | MOLDAVIUM | AUSTRIUM | ALKALINIUM | ALABAMIUM |
  ILLINIUM | CAROLINIUM | GNOMIUM | MONIUM | MURIUM | MURIATICUM | PTENE | POLINIUM |
  PHLOGISTON | VIS VIVA | AETHER DRIFT | AETHER DRAG | AETHER WIND | MIASMA | TRIA PRIMA |
  HORROR VACUI | IMPONDERABLE | NASCENT STATE | ENERGETICISM | VITALISM | NEPTUNISM |
  GRANITIZATION | GEOSYNCLINE | MONOGLACIATION | ZYMOTIC | LINE OF FORCE |
  OPEN POLAR SEA | EPICYCLE | DEFERENT | PRIMUM MOBILE | PREFORMATION | RECAPITULATION`);
